name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt install libssl-dev libboost-system-dev
    - name: Build App
      run: make app
    - name: Configure Locales
      run: echo ru_RU.UTF-8 UTF-8 | sudo tee --append /etc/locale.gen && locale-gen
    - name: Run App
      run: ./dist/app
      
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Tests
      run: make tests
    - name: Run Tests
      run: ./dist/test_app
